# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_text',
            field=models.CharField(default='default-extra', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published, yo'),
        ),
    ]
